version: "3"
services:
  rediscache:
    image: redis:latest
    container_name: rediscache
    restart: always
  proxypool:
    build: .
    container_name: proxypool
    ports:
      - "5555:5555"
    restart: always
    environment:
      PROXYPOOL_REDIS_CONNECTION_STRING: redis://@rediscache:6379/0
